pytest_splunk_addon_ui_smartx/base_test.py

To ignore the SSL Warning in Firefox with Saucelabs

Ignore ssl warnings in firefox (saucelabs)

---

pytest_splunk_addon_ui_smartx/alert_actions/components/action_controls.py

Updated the alert actions help and label text elements so that it finds the nodes more often, and makes them more general when finding them.

fix: Updating alert actions help and label texts

---

.circleci/config.yml

latest version of semantic-release is broken on node11 image.

ci: Updated image to node12 in release stage.

---

pytest_splunk_addon_ui_smartx/components/table.py

Updated table.py's delete_row() function.
"delete_btn" to "waitspinner"

fix: updated delete_btn to waitspinner for delete TC

---

.circleci/config.yml

The release stage failed due to buggy version of semantic-release in the this CI run : https://app.circleci.com/pipelines/github/splunk/addon-factory-smartx-ui-test-library/514/workflows/7916e20e-3721-45d1-8fd6-c3029058209d

downgrade semantic-release version to resume release stage as latest version is having some issues

---

pytest_splunk_addon_ui_smartx/alert_actions/components/account_select.py

Changing the selector for the Alert Actions Select Account dropdown, as the old selector is stale and is no longer able to find the element.

INFRA-33660 Fixing UI element for Alert Actions dropdown element

---

pytest_splunk_addon_ui_smartx/alert_actions/components/account_select.py

* Fixing cancel_selected selector for Alert Actions dropdown by updating the selector to something more uniform between differing Splunk versions including Olympus builds.

INFRA-33748-troubleshoot-failures-on-NOAH-SHC Alert Actions fix

---

poetry.lock
pyproject.toml

This commit unblocks PSA 3.x.x versions to be installed.
PSA's breaking changes should not impoact this repo.

fix: allow PSA >=2,<4 versions

---

poetry.lock
pyproject.toml

This PR updates PSA to 3.0.0 and adds `lxml` as well (`lxml` is used in smartx, but not directly declared in the dependencies and after removal of `splunk-appinspect` from PSA, there is no `lxml` available for smartx).

feat: update PSA to 3.0.0

---

.github/dependabot.yml
.github/workflows/build-test-release.yaml

- ci: update semantic version and remove node 14 workaround
- ci: add dependabot conf for github-actions

ci: update semantic version and remove node 14 workaround

---

.addonmatrix
.github/workflows/agreements.yaml
.github/workflows/build-test-release.yaml
.github/workflows/exclude-patterns.txt
docker-compose-ci.yml

This PR removes selenium grid-based tests from this pipeline and uses meta job to determine the version of Splunk the tests should target.

ci: remove selenium grid from CI

---

.github/workflows/build-test-release.yaml
pytest_splunk_addon_ui_smartx/components/controls/multi_select.py
tests/ui/test_splunk_ta_example_addon_custom.py

Corresponding to Github [Issue-390](https://github.com/splunk/addon-factory-smartx-ui-test-library/issues/390)
- Tested clear_text function and it's working properly

feat(code): added clear_text function

---

docker-compose-ci.yml
tests/ui/test_splunk_ta_example_addon_alert_actions.py

Using `SPLUNK_DISABLE_POPUPS` env variable to control popups, setting it to `true` so we don't need to have workaround code to bypass those.
Check out docs here: https://github.com/splunk/splunk-ansible/blob/186c95b84d82f9201e036388c716d466d083ae37/docs/ADVANCED.md?plain=1#L101

test: use SPLUNK_DISABLE_POPUPS=true and remove workaround

---

.github/workflows/build-test-release.yaml

This way the tests should be more stable.

ci: run 8 parallel UI test jobs

---

pytest_splunk_addon_ui_smartx/components/login.py

We wait for some time every time when we login, but that ToS is not there. This should speed up the test execution especially in the case of not persisting browser.

fix: remove enterprise cloud ToS code for login page

---

pytest_splunk_addon_ui_smartx/components/controls/multi_select.py
pytest_splunk_addon_ui_smartx/components/controls/oauth_select.py
pytest_splunk_addon_ui_smartx/components/controls/single_select.py
pytest_splunk_addon_ui_smartx/components/dropdown.py

fix(popover): fix selectors for popover

---

.github/workflows/build-test-release.yaml

This PR introduces a cache before all `poetry install` steps so we save a bunch of time not downloading the same dependencies all the time.

ci: introduce cache for unit tests, build and UI tests steps

---

pytest_splunk_addon_ui_smartx/components/controls/single_select.py
pytest_splunk_addon_ui_smartx/components/dropdown.py
tests/testdata/Splunk_TA_UCCExample/globalConfig.json
tests/ui/test_splunk_ta_example_addon_input_1.py
tests/ui/test_splunk_ta_example_addon_input_common.py

The same as in #412.
- Fix SingleSelect is_editable() checking if field can be modified on edit
- Add SingleSelect allow_new_values() checking if field accepts custom values
- add corresponding UI tests
- override BaseComponents wait_to_be_stale() in Dropdown and add to flaky tests to resolve a Stale Element Error
Reference:
* https://splunk.atlassian.net/browse/ADDON-66912
* https://splunk.atlassian.net/browse/ADDON-65416
Released as beta and tested:
* https://github.com/splunk/splunk-add-on-for-amazon-web-services/pull/1126
* https://github.com/splunk/splunk-add-on-for-okta-identity-cloud/pull/231

fix: ADDON-66912 SingleSelect is_editable fix and add SingleSelect allow_new_values

---

pytest_splunk_addon_ui_smartx/components/controls/multi_select.py
pytest_splunk_addon_ui_smartx/components/dropdown.py
pytest_splunk_addon_ui_smartx/components/table.py

This PR provides exception handling for multiselect and dropdown to get rid of flaky test cases.
Additionaly wait_to_be_clickable added in table module.

fix: fixes for flaky table, multiselect, dropdown

---

pytest_splunk_addon_ui_smartx/components/controls/single_select.py
pytest_splunk_addon_ui_smartx/components/dropdown.py
tests/testdata/Splunk_TA_UCCExample/globalConfig.json
tests/ui/test_splunk_ta_example_addon_input_1.py

Fix for reported issue with is_editable() of SingleSelect: https://splunk.atlassian.net/browse/ADDON-68980
Issue was present when SingleSelect element was configured to allow new values - updated tests scenarios.

fix: ADDON-68980 single_select is_editable fix for combobox

---

pytest_splunk_addon_ui_smartx/components/table.py

Updated using of `find_element` to `find_elements` to avoid the `NoSuchElementException` when the element isn't found in the page.

fix(table): update element finding function

---

.releaserc

Current regex is not matching beta releases - this PR fixes that.
Test run: https://github.com/splunk/test-addonfactory-repo/actions/runs/9516876272

ci: align semantic regex for version update

---

pytest_splunk_addon_ui_smartx/base_test.py

Specifying window resolution for UI tests resolves `ElementNotInteractableException` error when element to be found with xpath is not visible and browser page has to be scrolled down.

fix: define browser resolution for all chrome tests

---

pytest_splunk_addon_ui_smartx/components/input_table.py

As requested in https://splunk.atlassian.net/browse/ADDON-71796.
input_status_toggle() is no longer based on literal value of `data-test`, instead it's based on actual status of the button `data-selected` attribute.
Tests in ucc:
https://github.com/splunk/addonfactory-ucc-generator/runs/27207848699
Without fix:
https://github.com/splunk/addonfactory-ucc-generator/runs/26432377281

fix: dynamic handle input status toggle [ADDON-71796]

---

docs/change_log.md
mkdocs.yml
poetry.lock
pyproject.toml
pytest_splunk_addon_ui_smartx/alert_actions/components/account_select.py
pytest_splunk_addon_ui_smartx/alert_actions/components/textbox.py
pytest_splunk_addon_ui_smartx/components/controls/single_select.py
pytest_splunk_addon_ui_smartx/components/controls/textarea.py
pytest_splunk_addon_ui_smartx/components/controls/textbox.py
tests/testdata/Splunk_TA_UCCExample/globalConfig.json
tests/ui/test_splunk_ta_example_addon_account.py
tests/ui/test_splunk_ta_example_addon_custom.py
tests/ui/test_splunk_ta_example_addon_input_1.py
tests/ui/test_splunk_ta_example_addon_input_2.py
tests/ui/test_splunk_ta_example_addon_proxy.py

ADDON-71391
Removes the placeholder related functionalities and the test cases present.
Users would no longer be able to use the `get_placeholder_value` property for their test cases.
**NOTE:** This PR can be merged once UCC 5.48.0 is released and updating the same version for this repo.
BREAKING CHANGE: remove placeholder functionality

feat: remove placeholder functionality from framework

---

.github/workflows/build-test-release.yaml

Updated the build-test-release workflow to use [sast-scan](https://github.com/splunk/sast-scanning) owned by product security team instead of using custom implementation.
Ref: https://splunk.atlassian.net/browse/ADDON-72309

ci: use reusable workflow for semgrep

---

pytest_splunk_addon_ui_smartx/base_test.py
pytest_splunk_addon_ui_smartx/utils.py
tests/ui/test_splunk_ta_example_addon_input_1.py
tests/ui/test_splunk_ta_example_addon_logging.py

[ADDON-73881](https://splunk.atlassian.net/browse/ADDON-73881)
As a smartx enjoyer, I want to get access to the browser console logs to fail my tests if there are JS errors.
- Add capability to track logs in Chrome
- Add a helper to access an array of logs
```python
severe_console_logs = get_browser_logs(ucc_smartx_selenium_helper.browser, log_level=LogLevel.SEVERE, log_source=LogSource.CONSOLE_API)
assert not severe_console_logs, f"Unexpected severe console logs found: {severe_console_logs}"
```
Currently, this feature is only supported with the Chrome browser.
Analysis on adding support for other browser: https://splunk.atlassian.net/browse/ADDON-73881?focusedCommentId=15449369

feat: add ability to get console logs

---

.github/workflows/build-test-release.yaml

This PR sets ubuntu version to 22.04 for scripts run with python 3.7.
Reference: [ADDON-75861](https://splunk.atlassian.net/browse/ADDON-75861)

ci: fix ubuntu version to 22.04

---

pytest_splunk_addon_ui_smartx/utils.py

[The run](https://github.com/splunk/addonfactory-ucc-generator/pull/1445/checks?check_run_id=33318042641) throws the errors of unknown source
`ValueError: 'javascript' is not a valid LogSource`
<details><summary>Full logs</summary>
<p>
```
test_alert_actions_page.chrome_TestAlertActions
✅ test_alert_action_save
test_configuration_page_account_tab.chrome_TestAccount
❌ test_account_filter_functionality_negative
ValueError: 'javascript' is not a valid LogSource
✅ test_account_edit_valid_title
❌ test_account_delete_close_entity
ValueError: 'javascript' is not a valid LogSource
❌ test_account_required_field_example_multiple_select
ValueError: 'javascript' is not a valid LogSource
❌ test_add_account_duplicate_name
ValueError: 'javascript' is not a valid LogSource …
```

fix(browser_logs): add log source javascript
