splunk/addon-factory-smartx-ui-test-library

pytest_splunk_addon_ui_smartx/components/controls/message.py
- Added explicit wait for close error before clicking button.
=> Added wait before click (close-error)

.readthedocs.yml, docs/requirements.txt
Adding support for documentation to be published on ReadTheDocs
=> Adding publish support for ReadTheDocs

pytest_splunk_addon_ui_smartx/components/table.py
Added method check_alert_sign() in table.py file which returns true if the row contains the alert warning.
=> Added support for warning sign in a table

pytest_splunk_addon_ui_smartx/components/message_tray.py
Adding SmartX Enhancements to support messageTray component
* Reads and finds the messages present on the message page
* Can geet the count of messages present in Message Tray
* Ensures that the message tray is showing the correct icon. 
* Can Delete messages within message tray
=> Adding messageTray enhancement

README.md, docs/conf.py, docs/example_code.py, docs/getting_started.rst, docs/how_to_use.rst, docs/index.rst, docs/overview.rst, poetry.lock, pyproject.toml, pytest_splunk_addon_ui_smartx/components/entity.py
* Created more documentation with SmartX
* Improved the Readme file for SmartX
* Helped remedy some spelling mistakes and made some updates on the documentation
* Added a Sphinx capability to have dropdowns, so that long code examples can be neatly tucked into the documentation.
=> Adding Getting Started Page to SmartX documentation

docs/api_reference.rst, docs/components/controls/index.rst, docs/components/index.rst, docs/pages/index.rst
Updating the toctrees so that we can maintain the same directory structure we follow in SMartX in API reference.
=> Updating docs

.circleci/config.yml, Dockerfile-tests, tests/entrypoint.sh
- Updated package stage for example addon in config file as per latest UCC version.
- Updated TEST_SET in entrypoint.sh and config.yml as per latest test folder structure. 
- Added **--use-deprecated=legacy-resolver** param to resolve conflicts due to latest pip version in Dockerfile-tests.
=> Updating build-stage in config file for example addon.

pytest_splunk_addon_ui_smartx/base_test.py, pytest_splunk_addon_ui_smartx/components/controls/checkbox.py
Fixed Assert_util function to prevent False pass in Timeout
=> fix: Fixed Assert_util function to prevent False pass in Timeout

poetry.lock, pyproject.toml, pytest_splunk_addon_ui_smartx/alert_actions/components/account_select.py, pytest_splunk_addon_ui_smartx/alert_actions/components/action_controls.py, pytest_splunk_addon_ui_smartx/alert_actions/components/button.py, pytest_splunk_addon_ui_smartx/alert_actions/components/checkbox.py, pytest_splunk_addon_ui_smartx/alert_actions/components/dropdown.py, pytest_splunk_addon_ui_smartx/alert_actions/components/searchbox.py, pytest_splunk_addon_ui_smartx/alert_actions/components/single_select.py, pytest_splunk_addon_ui_smartx/alert_actions/components/table.py, pytest_splunk_addon_ui_smartx/alert_actions/components/textbox.py, pytest_splunk_addon_ui_smartx/alert_actions/components/toggle.py
feat: Added the logic for finding help_text and label elements within Action Alerts for SmartX
=> feat: Adding help_text and label checks

.gitmodules
Update UCC-Example addon submodule branch to main
=> test: update UCC-Example addon submodule branch to main

.gitmodules, tests/unit/test_base_test.py, tests/unit/test_utils.py
Added unit test for test_base.py
=> Feature/unit tests/infra 31176

pytest_splunk_addon_ui_smartx/components/table.py
Jira: https://jira.splunk.com/browse/ADDON-38879
- updated the status field value in get_table method
=> Updated status field value in get_table method

pytest_splunk_addon_ui_smartx/components/base_component.py, pytest_splunk_addon_ui_smartx/components/controls/textbox.py, pytest_splunk_addon_ui_smartx/components/table.py
Jira: https://jira.splunk.com/browse/ADDON-39006
- handled removing of default value of textbox before setting new value for Safari browser
- removed child node text while getting list of headers from the table 
- fixed text of web element in get_clear_text method
=> Fix failures of UI tests on safari browser

pytest_splunk_addon_ui_smartx/components/login.py
Update login.py file to handle TOS agreement page in Splunk cloud
Validation:
The below scenarios are validated with the ServiceNow addon v7.1.0.
- Single Search head (8.2.2106):
- When TOS agreement page is present:
- Chrome: https://assets.saucelabs.com/jobs/231ecae43f9445db8afcd5f0801dd225/video.mp4
- Edge: https://assets.saucelabs.com/jobs/4422961d255b4d77976795858d5a940c/video.mp4
- Firefox: https://assets.saucelabs.com/jobs/77e36f5db9c8456da4a1018d5afcaec8/video.mp4
- Safari: https://assets.saucelabs.com/jobs/544b4eeeafe14ca5a5c9bd02ca900f68/video.mp4
- When TOS agreement page is not present:
- Chrome: https://assets.saucelabs.com/jobs/76303b9d57d247778d75c537dff243f9/video.mp4
- Edge: https://assets.saucelabs.com/jobs/65da2e20ae4b477c931574395d4b9608/video.mp4
- Firefox: …
=> fix: handled tos agreement page in splunk cloud

pytest_splunk_addon_ui_smartx/base_test.py, tests/unit/test_base_test.py
Added chrome_grid and firefox_grid new browsers types as a first phrase to switch to local stack
=> feat: chrome_grid and firefox_grid support for selenium local stack

Dockerfile-tests
fix: fixing CircleCI tests for SmartX
=> INFRA-34049 Fixing CircleCI issues with SmartX

pytest_splunk_addon_ui_smartx/base_test.py, pytest_splunk_addon_ui_smartx/plugin.py
feat: Adding a dynamic way to get latest Safari version in Saucelabs
=> INFRA-34336 Updating Safari Version with latest 

.github/workflows/build-test-release.yaml
=> ci: multiple updates

poetry.lock, pyproject.toml, pytest_splunk_addon_ui_smartx/plugin.py
This PR removes PSA as a dependency from smartx as it is not used here.
=> feat: remove PSA

.github/workflows/build-test-release.yaml, .github/workflows/sr-prepare.sh, .github/workflows/sr-release.sh, .releaserc
* chore: add internal semantic and pypi-publish actions
* chore: add wget issues handling to ci
* chore: add authentication to curl
* chore: introduce cache for ta example
* chore: fix download Splunk_TA example step
* chore: unpack Splunk_TA example
* chore: refactor ui setup testing
* chore: fix ui setup for testing
* chore: fix SPLUNK_APP_PACKAGE path
* chore: take prerequisites-ui-tests job version output
=> fix: add internal semantic-release-action and pypi-publish-action (#350)

.releaserc, pytest_splunk_addon_ui_smartx/base_test.py, pytest_splunk_addon_ui_smartx/components/controls/toggle.py
UCC UI was updated and the HTML was changed, this is an attempt to fix it.
=> fix: update for Toggle component

.gitignore, pytest_splunk_addon_ui_smartx/components/base_component.py, pytest_splunk_addon_ui_smartx/components/table.py, tests/testdata/Splunk_TA_UCCExample/package/app.manifest
- Added search button in input page action column.
=> feat: added new search button in action column

pytest_splunk_addon_ui_smartx/components/controls/message.py, pytest_splunk_addon_ui_smartx/components/controls/multi_select.py
- Updated component selectors with respect to `@splunk/react-ui==4.30.0`.
=> fix(path): update label buttons w.r.t. SUI 4.30.0
